version: "3"
services:
    db:
        image:
            postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: islamic_library
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin:
        image:
            dpage/pgadmin4
        ports:
            - "80:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: library@gmail.com
            PGADMIN_DEFAULT_PASSWORD: postgres

volumes:
    postgres-data:
        driver: local
